configMapGenerator:
- files:
  - application.yml
  name: cloud-sample-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/24103014
  newTag: "202410302320"
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202408120727"
