apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 82240958-ingress
spec:
  ingressClassName: ingress-internal
  rules:
  - host: 82240958.cepg-aa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: "82240958"
            port:
              number: 8080
        pathType: Prefix